services:

  fastfetch:
    image: bigbeartechworld/big-bear-fastfetch:0.0.2
    container_name: fastfetch
    restart: unless-stopped
    privileged: true
    volumes:
      - /proc:/proc
      - /sys:/sys
      - /dev:/dev
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "7681:7681"

